import PokeFooter from '@/components/home/PokeFooter';
import MyCollectionSection from '@/components/my-collection/MyCollectionSection';
import Profile from '@/components/my-collection/Profile';
import { APP_NAME } from '@/helper/constants';
import useWindowSize from '@/helper/useWindowSize';
import { Col, Row } from 'antd';
import Head from 'next/head';

const MyCollectionHead = () => {
    return (
        <Head>
            <title>My Collection - {APP_NAME}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

const MyCollection = () => {
    const windowSize = useWindowSize();

    return (
        <>
            <MyCollectionHead />
            <main>
                <Row justify="center">
                    <Col style={{ width: windowSize.width >= 800 ? 800 : '100vw' }}>
                        <Row gutter={[0, 32]}>
                            <Col span={24}>
                                <Profile />
                            </Col>
                            <Col span={24}>
                                <MyCollectionSection />
                            </Col>
                            <Col span={24}>
                                <PokeFooter />
                            </Col>
                        </Row>
                    </Col>
                </Row>
            </main>
        </>
    );
};

export default MyCollection;
