import PokeFooter from '@/components/home/PokeFooter'
import PokeHeader from '@/components/home/PokeHeader'
import PokeList from '@/components/home/PokeList'
import HomeContextProvider from '@/context/home/HomeContextProvider'
import { APP_NAME } from '@/helper/constants'
import { Col, Row } from 'antd'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - {APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeContextProvider>
          <Row>
            <Col span={24}>
              <PokeHeader />
            </Col>
            <Col span={24}>
              <PokeList />
            </Col>
            <Col span={24}>
              <PokeFooter />
            </Col>
          </Row>
        </HomeContextProvider>
      </main>
    </>
  )
}
