import PokeFooter from '@/components/home/PokeFooter'
import PokeHeader from '@/components/home/PokeHeader'
import PokeList from '@/components/home/PokeList'
import HomeContextProvider from '@/context/home/HomeContextProvider'
import { APP_NAME } from '@/helper/constants'
import useWindowSize from '@/helper/useWindowSize'
import { Col, Row } from 'antd'
import Head from 'next/head'
import styled from 'styled-components'

const HomeHead = () => {
  return (
    <Head>
      <title>Home - {APP_NAME}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

const HomeForMobile = () => {
  const size = useWindowSize()

  const heightContent = size.height - (60 + 70 + (16 * 2))
  const HomeWrapper = styled.div`
    .content{
      height: ${heightContent}px;
      overflow-y: auto;
      overflow-x: hidden;
    }
  `

  return (
    <HomeWrapper>
      <Row gutter={[0, 16]}>
        <Col span={24}>
          <PokeHeader />
        </Col>

        <div className='content'>
          <Col span={24}>
            <PokeList />
          </Col>
        </div>

        <Col span={24}>
          <PokeFooter />
        </Col>
      </Row>
    </HomeWrapper>
  )
}

export default function Home() {
  const windowSize = useWindowSize()

  return (
    <>
      <HomeHead />
      <main>
        <HomeContextProvider>
          <Row justify="center">
            <Col style={{ width: windowSize.width >= 800 ? 800 : '100vw' }}>
              <HomeForMobile />
            </Col>
          </Row>
        </HomeContextProvider>
      </main>
    </>
  )
}
