import DetailDescription from '@/components/detail/DetailDescription'
import DetailNavbar from '@/components/detail/DetailNavbar'
import beautifyPokemonTypeObj from '@/helper/beautifyPokemonTypeObj'
import beautifyWord from '@/helper/beautifyWord'
import { API_URL_POKE, APP_NAME } from '@/helper/constants'
import { Col, Row } from 'antd'
import { PokemonType } from 'app-types'
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'

type DetailProps = {
    pokemon: PokemonType
}

export default function Detail({ pokemon }: DetailProps) {

    return (
        <>
            <Head>
                <title>Detail - {APP_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Row justify='center' gutter={[0, 18]}>
                    <Col span={24}>
                        <DetailNavbar />
                    </Col>
                    <Col span={24}>
                        <DetailDescription data={pokemon} />
                    </Col>
                </Row>
            </main>
        </>
    )
}

export async function getServerSideProps(context: any) {
    const { params: { id } } = context

    try {
        const baseUrl = `${API_URL_POKE}pokemon/${id}`
        const { data } = await axios.get(baseUrl);

        return {
            props: {
                pokemon: beautifyPokemonTypeObj(data),
            }
        }
    } catch (error) {
        console.error(error);
        return {
            props: {}
        }
    }
}
